services:
  mysql:
    image: mysql:8.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quant
      MYSQL_USER: quant
      MYSQL_PASSWORD: quant
    ports: ["3306:3306"]
    volumes:
      - ./.db/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
  mlflow:
    image: ghcr.io/mlflow/mlflow
    restart: unless-stopped
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlruns
    ports: ["5000:5000"]
    volumes:
      - ./.mlruns:/mlruns
volumes: {}
