from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any, Mapping
import sys
import types

if "pymysql" not in sys.modules:
    pymysql_stub = types.ModuleType("pymysql")
    pymysql_stub.connect = lambda *args, **kwargs: None
    cursors_stub = types.ModuleType("pymysql.cursors")
    cursors_stub.DictCursor = object
    pymysql_stub.cursors = cursors_stub
    sys.modules["pymysql"] = pymysql_stub
    sys.modules["pymysql.cursors"] = cursors_stub

from quant_engine.api import app
from quant_engine.config import reset_settings_cache
from quant_engine.persistence import (
    MarketStatsRepository,
    MetricsRepository,
    RunsRepository,
    SeasonalityProfilesRepository,
    SeasonalityRunsRepository,
    session,
)

GOLDEN_PATH = Path("tests/data/golden/analytics_stats_seasonality_snapshots.json")

# These fields are generated by persistence at runtime and are expected to vary
# between executions, platforms, and SQLite implementations.
VOLATILE_FIELDS = {
    "id",  # SQLite AUTOINCREMENT primary key (seasonality_profiles.id).
    "created_at",  # Generated insertion timestamp in run/profile tables.
    "started_at",  # Generated insertion timestamp in experiment_runs.
    "finished_at",  # Updated completion timestamp in experiment_runs.
}


RUN_ID = "analytics-snapshot-run"


def _normalize_snapshot(value: Any) -> Any:
    if isinstance(value, Mapping):
        normalized: dict[str, Any] = {}
        for key, item in value.items():
            if key in VOLATILE_FIELDS:
                continue
            normalized[key] = _normalize_snapshot(item)
        return normalized
    if isinstance(value, list):
        return [_normalize_snapshot(item) for item in value]
    return value


def _snapshot_payload() -> dict[str, Any]:
    return {
        "analytics": {
            "run": app.get_run(RUN_ID),
            "metrics": app.get_run_metrics(RUN_ID),
        },
        "stats": {
            "summary": app.stats_summary(symbol="BTCUSDT", timeframe="1h", event="breakout"),
            "heatmap": app.stats_heatmap(
                symbol="BTCUSDT",
                timeframe="1h",
                event="breakout",
                target="up",
                condition_name="volatility_bin",
            ),
            "top": app.stats_top(symbol="BTCUSDT", timeframe="1h", k=2),
        },
        "seasonality": {
            "runs": app.list_seasonality_runs(spec_id="seasonality-spec-snapshot"),
            "detail": app.get_seasonality_run("seasonality-snapshot-run"),
            "profiles": app.list_seasonality_profiles(symbol="BTCUSDT", timeframe="1h"),
        },
    }


def _assert_snapshot(actual: Mapping[str, Any]) -> None:
    # Controlled updates: both flags must be set to avoid accidental snapshot drift.
    should_update = (
        os.getenv("QE_UPDATE_SNAPSHOTS", "0") == "1"
        and os.getenv("QE_UPDATE_ANALYTICS_SNAPSHOTS", "0") == "1"
    )
    if should_update:
        GOLDEN_PATH.write_text(json.dumps(actual, indent=2, sort_keys=True) + "\n")
    expected = json.loads(GOLDEN_PATH.read_text())
    assert actual == expected


def test_analytics_stats_seasonality_snapshots_are_stable(tmp_path, monkeypatch) -> None:
    monkeypatch.setenv("DB_SQLITE_PATH", str(tmp_path / "snapshots.sqlite"))
    monkeypatch.delenv("DB_DSN", raising=False)
    reset_settings_cache()

    with session() as conn:
        runs_repo = RunsRepository(conn)
        metrics_repo = MetricsRepository(conn)
        stats_repo = MarketStatsRepository(conn)
        seasonality_runs_repo = SeasonalityRunsRepository(conn)
        seasonality_profiles_repo = SeasonalityProfilesRepository(conn)

        runs_repo.create_or_running(
            run_id=RUN_ID,
            spec_id="analytics-spec",
            dataset_id="analytics-dataset",
            objective="sharpe",
            out_dir="/tmp/analytics",
        )
        metrics_repo.bulk_upsert_metrics(
            RUN_ID,
            {
                "sharpe": 1.42,
                "max_dd": 0.12,
                "return": 0.31,
            },
        )
        runs_repo.finish(RUN_ID, "FINISHED")

        stats_repo.bulk_upsert(
            [
                {
                    "symbol": "BTCUSDT",
                    "timeframe": "1h",
                    "event": "breakout",
                    "condition_name": "volatility_bin",
                    "condition_value": "low",
                    "target": "up",
                    "split": "test",
                    "n": 30,
                    "successes": 18,
                    "p_hat": 0.6,
                    "ci_low": 0.42,
                    "ci_high": 0.75,
                    "lift": 0.12,
                    "start": "2024-01-01",
                    "end": "2024-02-01",
                },
                {
                    "symbol": "BTCUSDT",
                    "timeframe": "1h",
                    "event": "breakout",
                    "condition_name": "volatility_bin",
                    "condition_value": "high",
                    "target": "up",
                    "split": "test",
                    "n": 25,
                    "successes": 10,
                    "p_hat": 0.4,
                    "ci_low": 0.24,
                    "ci_high": 0.58,
                    "lift": -0.08,
                    "start": "2024-01-01",
                    "end": "2024-02-01",
                },
            ]
        )

        seasonality_runs_repo.create(
            "seasonality-snapshot-run",
            spec_id="seasonality-spec-snapshot",
            dataset_id="seasonality-dataset-snapshot",
            out_dir="/tmp/seasonality-snapshot",
        )
        seasonality_profiles_repo.bulk_upsert(
            [
                {
                    "symbol": "BTCUSDT",
                    "timeframe": "1h",
                    "dim": "hour",
                    "bin": 9,
                    "measure": "direction",
                    "score": 0.64,
                    "n": 480,
                    "baseline": 0.52,
                    "lift": 0.12,
                    "metrics": {"p_breakout_up": 0.33, "run_len_up_mean": 2.5},
                    "start": "2023-01-01",
                    "end": "2024-01-01",
                    "spec_id": "seasonality-spec-snapshot",
                    "dataset_id": "seasonality-dataset-snapshot",
                }
            ]
        )
        seasonality_runs_repo.finish(
            "seasonality-snapshot-run",
            "completed",
            {"best_metrics": {"sharpe": 1.1, "sortino": 1.6}},
        )

    snapshot = _normalize_snapshot(_snapshot_payload())
    _assert_snapshot(snapshot)
